"""filing chunks

Revision ID: df5d92782ed0
Revises: acc09b6fbdc9
Create Date: 2026-10-01 18:15:58.536805
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = 'df5d92782ed0'
down_revision: str | None = 'acc09b6fbdc9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'chunk_index')
    )
    op.create_index('ix_filing_chunks_embedding_hnsw', 'filing_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_filing_chunks_filing_id'), 'filing_chunks', ['filing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filing_chunks_filing_id'), table_name='filing_chunks')
    op.drop_index('ix_filing_chunks_embedding_hnsw', table_name='filing_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('filing_chunks')
    # ### end Alembic commands ###
