"""filings

Revision ID: 46a89ff92b0f
Revises: a1a0a841d4f3
Create Date: 2026-10-01 18:02:09.332667
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '46a89ff92b0f'
down_revision: str | None = 'a1a0a841d4f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('accession_number', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('form', sa.String(length=16), nullable=False),
    sa.Column('filed_on', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_filings_filed_on'), 'filings', ['filed_on'], unique=False)
    op.create_index(op.f('ix_filings_ticker'), 'filings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filings_ticker'), table_name='filings')
    op.drop_index(op.f('ix_filings_filed_on'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
