"""filing summaries

Revision ID: acc09b6fbdc9
Revises: 46a89ff92b0f
Create Date: 2026-10-01 18:07:28.075391
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'acc09b6fbdc9'
down_revision: str | None = '46a89ff92b0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('summary_headline', sa.String(length=255), nullable=True))
    op.add_column('filings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('filings', sa.Column('summary_model', sa.String(length=64), nullable=True))
    op.add_column('filings', sa.Column('summarized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('filings', sa.Column('summary_error', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'summary_error')
    op.drop_column('filings', 'summarized_at')
    op.drop_column('filings', 'summary_model')
    op.drop_column('filings', 'summary')
    op.drop_column('filings', 'summary_headline')
    # ### end Alembic commands ###
