"""article engagement

Revision ID: 0bb4110ab77a
Revises: df5d92782ed0
Create Date: 2026-10-01 19:49:46.474614
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0bb4110ab77a'
down_revision: str | None = 'df5d92782ed0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_engagement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('article_url', sa.String(length=2048), nullable=False),
    sa.Column('outlet', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_engagement_user_created', 'article_engagement', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_engagement_user_created', table_name='article_engagement')
    op.drop_table('article_engagement')
    # ### end Alembic commands ###
